module.exports = {
  salaireMensuel,
  loyer,
  nourriture,
  transport,
  autresDepenses,
  totalDepenses,
  reste,
  loisirs,
  totalDepensesAvecLoisirs,
  resteAvecLoisirs,
  bonus,
  nouveauSalaire,
  nouveauLoyer,
  nouvelleNourriture,
  nouveauTransport,
  depenses,
  resteFinal
};
